repository:
  name: "red"
  description: "Replicated state machine programming framework for Elixir"
  private: true
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: "master"
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: false
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: "bug"
    color: "#d73a4a"
    description: "Something isn't working"
  - name: "documentation"
    color: "#0075ca"
    description: "Improvements or additions to documentation"
  - name: "enhancement"
    color: "#a2eeef"
    description: "New feature or request"
  - name: "in-progress"
    color: "#661BF4"
    description: "Something that is being worked on"
  - name: "question"
    color: "#d876e3"
    description: "Further information is requested"
  - name: "todo"
    color: "#73F624"
    description: "Description of something that needs to be done"
  - name: "wontfix"
    color: "#ffffff"
    description: "This will not be worked on"
  - name: "writing"
    color: "#FBCA04"
    description: "Writing and report work"
  - name: "programming"
    color: "#006B75"
    description: "Programming work"
